#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************

# AARCH64 specific profile environment varialbles
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53"

# AARCH64 specific pipeline CI env. variables. "aarch64-none-elf" is not available there as it seems
[env.pipeline]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53"

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test", "--target", "x86_64-pc-windows-msvc",]

[tasks.doc]
command = "cargo"
args = ["doc", "--target", "aarch64-unknown-linux-gnu", "--open"]

[tasks.doctest]
command = "cargo"
args = ["test", "--doc"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.publish_dry]
command = "cargo"
args = ["publish", "--dry-run"]

[tasks.publish]
command = "cargo"
args = ["publish", "--token", "${CRATES_TOKEN}", "--allow-dirty"]